#TODO create Macro

set( NAME_ADDON ofxTwistedRibbon )
if( ${NAME_ADDON} IN_LIST OFX_ADDONS_ACTIVE )
    if( EXISTS ${OF_DIRECTORY_ABSOLUTE}/addons/${NAME_ADDON}/)
        include( ${OF_CMAKE_ADDONS}/external/${NAME_ADDON}.cmake )
        message( STATUS "${NAME_ADDON} activated" )
    else()
        message( WARNING "${NAME_ADDON} folder not found" )
    endif()
endif()

set( NAME_ADDON ofxOneEuroFilter )
if( ${NAME_ADDON} IN_LIST OFX_ADDONS_ACTIVE )
    if( EXISTS ${OF_DIRECTORY_ABSOLUTE}/addons/${NAME_ADDON}/)
        include( ${OF_CMAKE_ADDONS}/external/${NAME_ADDON}.cmake )
        message( STATUS "${NAME_ADDON} activated" )
    else()
        message( WARNING "${NAME_ADDON} folder not found" )
    endif()
endif()

set( NAME_ADDON ofxFlowTools )
if( ${NAME_ADDON} IN_LIST OFX_ADDONS_ACTIVE )
    if( EXISTS ${OF_DIRECTORY_ABSOLUTE}/addons/${NAME_ADDON}/)
        include( ${OF_CMAKE_ADDONS}/external/${NAME_ADDON}.cmake )
        message( STATUS "${NAME_ADDON} activated" )
    else()
        message( WARNING "${NAME_ADDON} folder not found" )
    endif()
endif()

set( NAME_ADDON ofxMidi )
if( ${NAME_ADDON} IN_LIST OFX_ADDONS_ACTIVE )
    if( EXISTS ${OF_DIRECTORY_ABSOLUTE}/addons/${NAME_ADDON}/)
        include( ${OF_CMAKE_ADDONS}/external/${NAME_ADDON}.cmake )
        message( STATUS "${NAME_ADDON} activated" )
    else()
        message( WARNING "${NAME_ADDON} folder not found" )
    endif()
endif()

set( NAME_ADDON ofxPiMapper )
if( ${NAME_ADDON} IN_LIST OFX_ADDONS_ACTIVE )
    if( EXISTS ${OF_DIRECTORY_ABSOLUTE}/addons/${NAME_ADDON}/)
        include( ${OF_CMAKE_ADDONS}/external/${NAME_ADDON}.cmake )
        message( STATUS "${NAME_ADDON} activated" )
    else()
        message( WARNING "${NAME_ADDON} folder not found" )
    endif()
endif()
